#!/bin/sh
set -eu

TEST_ADMOB_APP_ID="ca-app-pub-3940256099942544~1458002511"
TEST_PUBLIC_MAP_INTERSTITIAL_AD_UNIT_ID="ca-app-pub-3940256099942544/4411468910"
TEST_PUBLIC_MAP_BANNER_AD_UNIT_ID="ca-app-pub-3940256099942544/2934735716"

if [ -z "${MATOOL_API_BASE_URL:-}" ]; then
  echo "MATOOL_API_BASE_URL is required"
  exit 1
fi

if [ -z "${MATOOL_USER_GUIDE_URL:-}" ]; then
  echo "MATOOL_USER_GUIDE_URL is required"
  exit 1
fi

if [ -z "${MATOOL_CONTACT_URL:-}" ]; then
  echo "MATOOL_CONTACT_URL is required"
  exit 1
fi

if [ -n "${MATOOL_ADMOB_APP_ID:-}" ] || [ -n "${MATOOL_PUBLIC_MAP_INTERSTITIAL_AD_UNIT_ID:-}" ] || [ -n "${MATOOL_PUBLIC_MAP_BANNER_AD_UNIT_ID:-}" ]; then
  if [ -z "${MATOOL_ADMOB_APP_ID:-}" ]; then
    echo "MATOOL_ADMOB_APP_ID is required when release AdMob settings are provided"
    exit 1
  fi

  if [ -z "${MATOOL_PUBLIC_MAP_INTERSTITIAL_AD_UNIT_ID:-}" ]; then
    echo "MATOOL_PUBLIC_MAP_INTERSTITIAL_AD_UNIT_ID is required when release AdMob settings are provided"
    exit 1
  fi

  if [ -z "${MATOOL_PUBLIC_MAP_BANNER_AD_UNIT_ID:-}" ]; then
    echo "MATOOL_PUBLIC_MAP_BANNER_AD_UNIT_ID is required when release AdMob settings are provided"
    exit 1
  fi

  RELEASE_ADMOB_APP_ID="${MATOOL_ADMOB_APP_ID}"
  RELEASE_PUBLIC_MAP_INTERSTITIAL_AD_UNIT_ID="${MATOOL_PUBLIC_MAP_INTERSTITIAL_AD_UNIT_ID}"
  RELEASE_PUBLIC_MAP_BANNER_AD_UNIT_ID="${MATOOL_PUBLIC_MAP_BANNER_AD_UNIT_ID}"
else
  RELEASE_ADMOB_APP_ID="${TEST_ADMOB_APP_ID}"
  RELEASE_PUBLIC_MAP_INTERSTITIAL_AD_UNIT_ID="${TEST_PUBLIC_MAP_INTERSTITIAL_AD_UNIT_ID}"
  RELEASE_PUBLIC_MAP_BANNER_AD_UNIT_ID="${TEST_PUBLIC_MAP_BANNER_AD_UNIT_ID}"
fi

mkdir -p iOSApp/Config
cat > iOSApp/Config/Debug.xcconfig <<EOF
MATOOL_API_BASE_URL = ${MATOOL_API_BASE_URL}
MATOOL_USER_GUIDE_URL = ${MATOOL_USER_GUIDE_URL}
MATOOL_CONTACT_URL = ${MATOOL_CONTACT_URL}
MATOOL_ADMOB_APP_ID = ${TEST_ADMOB_APP_ID}
MATOOL_PUBLIC_MAP_INTERSTITIAL_AD_UNIT_ID = ${TEST_PUBLIC_MAP_INTERSTITIAL_AD_UNIT_ID}
MATOOL_PUBLIC_MAP_BANNER_AD_UNIT_ID = ${TEST_PUBLIC_MAP_BANNER_AD_UNIT_ID}
EOF

cat > iOSApp/Config/Release.xcconfig <<EOF
MATOOL_API_BASE_URL = ${MATOOL_API_BASE_URL}
MATOOL_USER_GUIDE_URL = ${MATOOL_USER_GUIDE_URL}
MATOOL_CONTACT_URL = ${MATOOL_CONTACT_URL}
MATOOL_ADMOB_APP_ID = ${RELEASE_ADMOB_APP_ID}
MATOOL_PUBLIC_MAP_INTERSTITIAL_AD_UNIT_ID = ${RELEASE_PUBLIC_MAP_INTERSTITIAL_AD_UNIT_ID}
MATOOL_PUBLIC_MAP_BANNER_AD_UNIT_ID = ${RELEASE_PUBLIC_MAP_BANNER_AD_UNIT_ID}
EOF
