name: main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode 16.4
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.4"

      - name: Cache SPM
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/org.swift.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Cache Pods
        uses: actions/cache@v3
        with:
          path: |
            Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Cache DerivedData
        uses: actions/cache@v3
        with:
          path: .derivedData
          key: ${{ runner.os }}-derived-${{ hashFiles('FesTracking2.xcodeproj/project.pbxproj', '**/*.swift', '**/*.h') }}
          restore-keys: |
            ${{ runner.os }}-derived-

      - name: Install CocoaPods
        run: |
          gem install cocoapods
          pod install

      - name: Build
        run: |
          xcodebuild build \
            -workspace FesTracking2.xcworkspace \
            -scheme FesTracking2 \
            -sdk iphoneos \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -derivedDataPath .derivedData \
            -skipMacroValidation \
            CODE_SIGNING_ALLOWED=NO \
            ENABLE_SWIFT_MACROS=YES
