name: main

on:
  push:
    branches: ["main", "feature/CI-CD"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode 16.4
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.4"

      - name: Install CocoaPods
        run: |
          gem install cocoapods
          pod install

      #project->workspaceに
      - name: Build
        run: |
          xcodebuild archive \
            -workspace FesTracking2.xcworkspace \
            -scheme FesTracking2 \
            -archivePath FesTracking2.xcarchive \
            -sdk iphoneos \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO
