name: main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "release"]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-26

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode 26.0
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "26.0"

      - name: Cache SPM
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/org.swift.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Cache DerivedData
        uses: actions/cache@v3
        with:
          path: .derivedData
          key: ${{ runner.os }}-derived-${{ hashFiles('FesTracking2.xcodeproj/project.pbxproj', '**/*.swift', '**/*.h') }}
          restore-keys: |
            ${{ runner.os }}-derived-

      - name: Build
        run: |
          xcodebuild build \
            -project FesTracking2.xcodeproj \   # ← workspace ではなく project に変更
            -scheme FesTracking2 \
            -sdk iphoneos \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -derivedDataPath .derivedData \
            -skipMacroValidation \
            CODE_SIGNING_ALLOWED=NO \
            ENABLE_SWIFT_MACROS=YES

