name: main

on:
  push:
    branches: ["main", "feature/CI-CD"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.8" # GitHub macOSランナーのRubyバージョンに合わせる

      - name: Install CocoaPods
        run: |
          gem install cocoapods
          pod install

      #project->workspaceに
      - name: Build
        run: |
          xcodebuild archive -workspace FesTracking2.xcworkspace -scheme FesTracking2 -archivePath FesTracking2.xcarchive -sdk iphoneos -configuration Release CODE_SIGNING_ALLOWED=NO
