name: Adhoc Distribution

on:
  push:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - uses: actions/cache@v3
        name: "Cache: SPM"
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData/AppName*/SourcePackages/
          #  ~/.swiftpm/
          key: ${{ runner.os }}-spm-${{ hashFiles('FesTracking2.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Bundle Install
        run: bundle install

      - name: Keychain.p12
        run: |
          echo "${{ secrets.P12_BASE64 }}" > ios_distribution.p12.txt
          base64 --decode -i ios_distribution.p12.txt -o ios_distribution.p12

      - name: ProvisioningProfile
        run: |
          echo "${{ secrets.PROVISIONING_BASE64 }}" > adhoc.mobileprovision.txt
          base64 --decode -i adhoc.mobileprovision.txt -o adhoc.mobileprovision

      - uses: actions/cache@v4
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install CocoaPods frameworks and build with custom scripts
        run: pod install

      - name: list files
        run: ls -l

      - name: Set Skipping Macro
        run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES

      - name: Enterprise Build and App Distribution
        env:
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          DISABLE_SWIFTLINT: true
        run: |
          npm install -g firebase-tools
          bundle exec fastlane archive_stg_app_distribution --verbose
      - name: Upload build logs
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: /Users/runner/Library/Logs/gym/FesTracking2-FesTracking2_AppDistribution.log
